server:
  port: 8081
spring:
  application:
    name: springcloud-user # 服务名称 横杠不可以是下划线

  datasource:
    url: jdbc:mysql://101.200.42.170:3306/springclouddb?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.coolron.user.domain
  mapper-locations: classpath:mapping/user/*.xml

eureka:
  client:
    # 指定服务注册中心的位置
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      
sms: 'It`s not pretty!'
